### ISSUE TITLE
Transcripts

### ISSUE THREAD

**Issue by francisdzheng** [ROC-HCI/UR-FUNNY#3]
Hi, 

I saw in a previous issue that the transcripts are now available, and I've downloaded the zip files linked in the README, but I can't seem to locate the transcripts. 

Where exactly are the transcripts located?

Thank you!

**Comment by matalvepu** [comment]
Sorry for not giving detailed descriptions. You will find the text of each video utterance in the language_sdk.pkl (UR-FUNNY-V2).
